version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_Db: regon
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/regon:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/regon"
      APP_URL: "http://regon.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "ndu5tb2ald1bt3i2279888xdia13le4b"
      APP_HOSTNAME: "regon.local"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/regon:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: